version: "3"

services:
  db:
    image: mariadb:10.5
    container_name: db
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - symfony_app
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: currency_exchange_php
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - 80:80
    networks:
      - symfony_app
    env_file:
      - .env.nginx.local

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:

networks:
  symfony_app:
    driver: bridge
